### ISSUE TITLE
Possible misunderstanding of Liskov Substitution Principle

### ISSUE THREAD

**Issue by radams78** [willayy/TDA553-Labs#12]
If the contracts for gas() and brake() are "they decrease or increase (by setting currentspeed variable) the speed of a vehicle object by a factor of speedFactor() every time you call it", then Scania and CarTransporter break these contracts and therefore break the Liskov Substitution Principle.

Looking at the code for gas() and brake() in Vehicle, however, it looks like you had a more complex contract in mind. What is this contract, and does your design follow LSP if we say this is the contract for gas() and brake() in Vehicle?

https://github.com/willayy/TDA553-lab1/blob/2c84dec901c6f81005eec4dbe8ca100ae1ea9ab5/Reflection/lab2reflection.txt#L2-L12

**Comment by willayy** [comment]
@radams78  i dont really see how Scania and CarTransporter break the contract? they all use the same gas and brake method from Vehicle class. The only difference is that they provide their own SpeedFactor (which is required by the abstract vehcicle class). And yes the contract is a bit more complex, would be something like.

"Method gas takes an argument of double amount, checks that this incrementation would not result in currentSpeed > engine power and then sets Currentspeed to amount * speedfactor".

Please let me know if this is correct or if this is an misunderstanding aswell!

**Comment by radams78** [comment]
I made a mistake - I thought that Scania and CarTransporter cannot gas and brake if the platform is in the wrong position. Instead, you have made it so that move(), turnLeft() and turnRight() do nothing if the platform is in the wrong position.

This is fine - good design - but I wanted you to think about whether this breaks LSP and, if not, why not.

So I would encourage you to think about this question: what is the contract for move(), turnLeft() and turnRight() in Vehicle? And do Scania and CarTransporter break this contract and therefore break LSP?

**Comment by willayy** [comment]
@radams78 i see! When i think about the question a new question arises, is it a contract violation that nothing happens? Should it maybe throw an exception instead? You wouldnt want to break the program so you would probably catch this exception and maybe then, do nothing. So i dont think it breaks the contract necessarily but i think the contract should be rewritten.

 the Contract for move() should be:

"Moves the vehicle for an amount of currentspeed, if the move() is used on a Truck that is a Vehicle the canMove() method must return True, otherwise nothing happens"

**Comment by radams78** [comment]
"is it a contract violation that nothing happens?"

That depends on the contract! You are designing the classes, you get to say
what the contract is.

"You wouldn't want to break the program"

Yes we do! If a method is called and a precondition is false, that means
there is a bug in the client code. We want the program to crash, and to
crash as close as possible to the source of the bug. We don't want the
program to do nothing when a bug happens - those are the hardest bugs to
find and fix. "Crash early, crash often". See Lecture 12 on unchecked
exceptions.

There is no difference between throwing an exception, catching it and then
doing nothing, and just doing nothing.

The contract for move() in Vehicle should not mention the Truck class. It
should not mention the canMove() method either - that is an implementation
detail. Contracts talk about what the object does when you call its public
methods. So I would write the contract for Vehicle to include something
like this:

A Vehicle object can be in one of two states, movable or unmovable.

The contract for the method gas(double amount):
Pre-condition: the Vehicle object must be movable; otherwise an
IllegalStateException is thrown.
Pre-condition: amount must be from 0 to 1 inclusive; otherwise an
IllegalArgumentException is thrown.
Post-condition: the speed of the Vehicle object is increased by amount *
its maximum acceleration, as long as this does not take it above its
enginePower; if it would, the speed is set to enginePower.

In the contract for Saab and Volvo:

A Saab object is always movable

In the contract for Truck:

A Scania object has a platform that can be at any angle from 0 to 70.

The Scania is movable iff the angle is 0.

Best,

/Robin

**Comment by radams78** [comment]
I'll add: for real software, we sometimes make it so that the exceptions crash the program while developing the software, but catch them and write a message to an error log for the published version, since there is not always time to fix all the bugs.

That's not ideal, though. Best practice, a bug should crash the program (or, better, stop it from compiling), in order to force us to fix it.

Merry Christmas!
